import {useEffect,useMemo,useState} from 'react';
import {Activity,ChevronRight,X} from 'lucide-react';
import {addMetricRecord} from './metricsRepository';
import {loadTrackers,type Tracker,type TrackerOptions} from './trackerRepository';

const localNow=()=>{const now=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return now.toISOString().slice(0,16)};
const expected=(tracker:Tracker)=>tracker.schedule?.frequency_type==='daily'||(tracker.schedule?.frequency_type==='specific_days'&&tracker.schedule.days_of_week.includes(new Date().getDay()));

function Recorder({tracker,unit,close,saved}:{tracker:Tracker;unit:string;close:()=>void;saved:()=>void}){const[value,setValue]=useState(''),[occurred,setOccurred]=useState(localNow()),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="sheet-shade" onMouseDown={close}><section className="metric-recorder" onMouseDown={e=>e.stopPropagation()}><button className="sheet-close" onClick={close}><X/></button><p className="eyebrow">LOG</p><h2>{tracker.name}</h2><p>This records an entry against the item you already configured.</p><label>Value<div className="metric-value"><input autoFocus type="number" step="any" value={value} onChange={e=>setValue(e.target.value)}/><span>{unit}</span></div></label><label>When<input type="datetime-local" value={occurred} onChange={e=>setOccurred(e.target.value)}/></label><label>Optional note<textarea value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<p className="goal-error">{error}</p>}<button className="save-record" disabled={busy||value===''||!Number.isFinite(Number(value))} onClick={async()=>{setBusy(true);try{await addMetricRecord(tracker,Number(value),new Date(occurred).toISOString(),note);saved()}catch(e){setError(e instanceof Error?e.message:'Unable to save entry')}finally{setBusy(false)}}}>{busy?'Saving…':'Log entry'}</button></section></div>}

export default function AllLogModule(){const[trackers,setTrackers]=useState<Tracker[]>([]),[options,setOptions]=useState<TrackerOptions>({areas:[],subcategories:[],units:[]}),[selected,setSelected]=useState<Tracker>(),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=async()=>{setLoading(true);try{const data=await loadTrackers();setTrackers(data.trackers.filter(x=>x.status==='active'));setOptions(data.options)}catch(e){setError(e instanceof Error?e.message:'Unable to load Log')}finally{setLoading(false)}};useEffect(()=>{load()},[]);const ordered=useMemo(()=>trackers.slice().sort((a,b)=>Number(expected(b))-Number(expected(a))||a.name.localeCompare(b.name)),[trackers]);const unit=(tracker:Tracker)=>options.units.find(x=>x.key===tracker.unit_key)?.symbol||tracker.custom_unit||'';if(loading)return <div className="page-wrap tracker-loading">Loading Log…</div>;return <div className="page-wrap all-log"><header className="page-head"><div><p className="eyebrow">LOG</p><h1>Record what happened.</h1><p>Expected items come first. Everything else remains available without crowding Today.</p></div></header>{error&&<p className="goal-error">{error}</p>}<div className="all-log-list">{ordered.map(tracker=><button key={tracker.id} onClick={()=>setSelected(tracker)}><span className="tracker-icon"><Activity/></span><div><small>{expected(tracker)?'EXPECTED TODAY':'AVAILABLE TO LOG'} · {tracker.module}</small><h2>{tracker.name}</h2><p>{tracker.measurement_type} {unit(tracker)} · {tracker.recordCount} previous entries</p></div><ChevronRight/></button>)}{!ordered.length&&<div className="empty-state"><Activity/><h2>Nothing configured yet</h2><p>Use + Add & Manage to create a logging item, or add a Habit.</p></div>}</div>{selected&&<Recorder tracker={selected} unit={unit(selected)} close={()=>setSelected(undefined)} saved={()=>{setSelected(undefined);load()}}/>}</div>}
