import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Archive, ChevronRight, Dumbbell, Plus, Search, X } from 'lucide-react';
import { formatDisplayLabel } from './displayLabels';
import { loadExerciseProfiles, muscleGroups, resistanceTypes, saveExerciseProfile, setExerciseArchived, weightConventions, type ExerciseProfile, type ExerciseProfileInput } from './exerciseRepository';

const number=(value:string)=>value===''?null:Number(value);
const numericValue=(value:number)=>Number.isFinite(value)?value:'';
const base=(item?:ExerciseProfile):ExerciseProfileInput=>({name:item?.name??'',muscle_group:item?.muscle_group??'other',secondary_muscle_group:item?.secondary_muscle_group??null,equipment:item?.equipment??null,resistance_type:item?.resistance_type??'other',default_sets:item?.default_sets??3,min_target:item?.min_target??8,max_target:item?.max_target??12,increment_kg:item?.increment_kg??0,minimum_weight:item?.minimum_weight??null,maximum_weight:item?.maximum_weight??null,available_weights:item?.available_weights??[],weight_convention:item?.weight_convention??'total_weight',measurement_type:item?.measurement_type??'Reps',progression_type:item?.progression_type??'Double Progression',notes:item?.notes??null});

function Editor({item,close,saved}:{item?:ExerciseProfile;close:()=>void;saved:()=>void}){
  const[form,setForm]=useState(base(item)),[weights,setWeights]=useState(form.available_weights.join(', ')),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const set=<K extends keyof ExerciseProfileInput>(key:K,value:ExerciseProfileInput[K])=>setForm(current=>({...current,[key]:value}));
  const setPrimary=(value:ExerciseProfileInput['muscle_group'])=>setForm(current=>({...current,muscle_group:value,secondary_muscle_group:current.secondary_muscle_group===value?null:current.secondary_muscle_group}));
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const available=weights.split(',').map(value=>value.trim()).filter(Boolean).map(Number);await saveExerciseProfile({...form,available_weights:available},item?.id);saved()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save exercise.')}finally{setBusy(false)}};
  return <div className="sheet-shade" onMouseDown={close}><form className="exercise-profile-editor" onMouseDown={event=>event.stopPropagation()} onSubmit={submit}><button type="button" className="sheet-close" onClick={close} aria-label="Close Exercise Profile"><X/></button><p className="eyebrow">{item?'EDIT':'ADD'} EXERCISE</p><h2>Exercise Profile</h2><div className="exercise-profile-grid">
    <label className="wide">Exercise name<input autoFocus value={form.name} onChange={event=>set('name',event.target.value)} required/></label>
    <label>Primary muscle group<select value={form.muscle_group} onChange={event=>setPrimary(event.target.value as ExerciseProfileInput['muscle_group'])}>{muscleGroups.map(value=><option value={value} key={value}>{formatDisplayLabel(value)}</option>)}</select></label>
    <label>Secondary muscle group<select value={form.secondary_muscle_group??''} onChange={event=>set('secondary_muscle_group',(event.target.value||null) as ExerciseProfileInput['secondary_muscle_group'])}><option value="">None</option>{muscleGroups.filter(value=>value!==form.muscle_group).map(value=><option value={value} key={value}>{formatDisplayLabel(value)}</option>)}</select></label>
    <label>Resistance type<select value={form.resistance_type??'other'} onChange={event=>set('resistance_type',event.target.value as ExerciseProfileInput['resistance_type'])}>{resistanceTypes.map(value=><option value={value} key={value}>{formatDisplayLabel(value)}</option>)}</select></label>
    <label>Weight convention<select value={form.weight_convention??'total_weight'} onChange={event=>set('weight_convention',event.target.value as ExerciseProfileInput['weight_convention'])}>{weightConventions.map(value=><option value={value} key={value}>{formatDisplayLabel(value)}</option>)}</select></label>
    <label>Default sets<input type="number" min="1" max="10" inputMode="numeric" value={numericValue(form.default_sets)} onChange={event=>set('default_sets',event.target.value===''?Number.NaN:Number(event.target.value))}/></label>
    <label>Minimum reps<input type="number" inputMode="numeric" value={form.min_target??''} onChange={event=>set('min_target',number(event.target.value))}/></label>
    <label>Maximum reps<input type="number" inputMode="numeric" value={form.max_target??''} onChange={event=>set('max_target',number(event.target.value))}/></label>
    <label>Minimum weight<input type="number" min="0" step="any" inputMode="decimal" value={form.minimum_weight??''} onChange={event=>set('minimum_weight',number(event.target.value))}/></label>
    <label>Weight increment<input type="number" min="0" step="any" inputMode="decimal" value={numericValue(form.increment_kg)} onChange={event=>set('increment_kg',event.target.value===''?Number.NaN:Number(event.target.value))}/></label>
    <label>Maximum / ceiling<input type="number" min="0" step="any" inputMode="decimal" value={form.maximum_weight??''} onChange={event=>set('maximum_weight',number(event.target.value))}/></label>
    <label className="wide">Custom available weights<input value={weights} inputMode="decimal" onChange={event=>setWeights(event.target.value)} onBlur={()=>setWeights(weights.split(',').map(value=>value.trim()).filter(Boolean).map(value=>String(Number(value))).join(', '))} placeholder="5, 7.5, 10, 12.5"/><small>When supplied, these override the fixed increment.</small></label>
    <label className="wide">Notes<textarea value={form.notes??''} onChange={event=>set('notes',event.target.value||null)}/></label>
  </div>{error&&<p className="goal-error">{error}</p>}<button className="save-record" disabled={busy}>{busy?'Saving…':'Save Exercise'}</button></form></div>;
}

export default function ExerciseLibrary({close}:{close:()=>void}){
  const[items,setItems]=useState<ExerciseProfile[]>([]),[query,setQuery]=useState(''),[group,setGroup]=useState(''),[resistance,setResistance]=useState(''),[archived,setArchived]=useState(false),[editing,setEditing]=useState<ExerciseProfile|null|undefined>(),[error,setError]=useState('');
  const load=()=>loadExerciseProfiles().then(setItems).catch(reason=>setError(reason instanceof Error?reason.message:'Unable to load Exercise Library'));
  useEffect(()=>{load()},[]);
  const visible=useMemo(()=>items.filter(item=>{const term=query.trim().toLowerCase();return Boolean(item.archived_at)===archived&&(!term||[item.name,item.muscle_group,item.secondary_muscle_group,item.resistance_type].some(value=>value?.toLowerCase().includes(term)))&&(!group||item.muscle_group===group||item.secondary_muscle_group===group)&&(!resistance||item.resistance_type===resistance)}),[items,query,group,resistance,archived]);
  return <div className="workout-full exercise-library"><header><div><p className="eyebrow">TRAINING</p><h1>Exercise Library</h1></div><button onClick={close} aria-label="Close Exercise Library"><X/></button></header><div className="exercise-library-toolbar"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search exercises"/></label><button className="soft-button" onClick={()=>setEditing(null)}><Plus/> Add Exercise</button></div><div className="exercise-library-filters"><select aria-label="Filter by muscle group" value={group} onChange={event=>setGroup(event.target.value)}><option value="">All muscle groups</option>{muscleGroups.map(value=><option key={value} value={value}>{formatDisplayLabel(value)}</option>)}</select><select aria-label="Filter by resistance type" value={resistance} onChange={event=>setResistance(event.target.value)}><option value="">All resistance types</option>{resistanceTypes.map(value=><option key={value} value={value}>{formatDisplayLabel(value)}</option>)}</select></div><div className="goal-tabs"><button className={!archived?'active':''} onClick={()=>setArchived(false)}>Active</button><button className={archived?'active':''} onClick={()=>setArchived(true)}>Archived</button></div>{error&&<p className="goal-error">{error}</p>}<section className="exercise-library-list">{visible.map(item=><article key={item.id}><button onClick={()=>setEditing(item)}><span><Dumbbell/></span><div><small>{formatDisplayLabel(item.muscle_group)}{item.secondary_muscle_group?` + ${formatDisplayLabel(item.secondary_muscle_group)}`:''} · {formatDisplayLabel(item.resistance_type??'other')}</small><h2>{item.name}</h2><p>{item.available_weights.length?`${item.available_weights.length} available weights`:item.increment_kg?`${item.increment_kg} kg increments`:'No load progression configured'}{item.maximum_weight!=null?` · ${item.maximum_weight} kg ceiling`:''} · {item.historyCount} configurations</p></div><ChevronRight/></button><button aria-label={`${archived?'Restore':'Archive'} ${item.name}`} onClick={()=>setExerciseArchived(item.id,!archived).then(load)}><Archive/></button></article>)}</section>{visible.length===0&&<p className="ui-empty">No exercises match these filters.</p>}{editing!==undefined&&<Editor item={editing??undefined} close={()=>setEditing(undefined)} saved={()=>{setEditing(undefined);load()}}/>}</div>;
}
