import{supabase}from'./supabase';
import{requireOwner}from'./trainingRepository';

const fail=(label:string,error:{message:string}|null)=>{if(error)throw new Error(`${label}: ${error.message}`)};
export type ResistanceType='machine'|'cable'|'dumbbell'|'barbell'|'plate_loaded'|'smith_machine'|'bodyweight'|'assisted_bodyweight'|'cardio_machine'|'other';
export type WeightConvention='total_weight'|'per_hand'|'per_side'|'bodyweight_only'|'bodyweight_added'|'bodyweight_assistance';
export type MuscleGroup='chest'|'back'|'shoulders'|'biceps'|'triceps'|'forearms'|'quadriceps'|'hamstrings'|'glutes'|'calves'|'core'|'full_body'|'cardio'|'other';
export type ExerciseProfile={id:string;exercise_key:string;name:string;muscle_group:MuscleGroup;secondary_muscle_group:MuscleGroup|null;equipment:string|null;resistance_type:ResistanceType|null;default_sets:number;min_target:number|null;max_target:number|null;increment_kg:number;minimum_weight:number|null;maximum_weight:number|null;available_weights:number[];weight_convention:WeightConvention|null;measurement_type:string;progression_type:string;notes:string|null;active:boolean;archived_at:string|null;historyCount:number};
export type ExerciseProfileInput=Omit<ExerciseProfile,'id'|'exercise_key'|'active'|'archived_at'|'historyCount'>;
export type ExerciseHistoryItem={id:string;performedOn:string;workoutName:string;sets:number;bestLoad:number|null;notes:string|null};
export const resistanceTypes:ResistanceType[]=['machine','cable','dumbbell','barbell','plate_loaded','smith_machine','bodyweight','assisted_bodyweight','cardio_machine','other'];
export const weightConventions:WeightConvention[]=['total_weight','per_hand','per_side','bodyweight_only','bodyweight_added','bodyweight_assistance'];
export const muscleGroups:MuscleGroup[]=['chest','back','shoulders','biceps','triceps','forearms','quadriceps','hamstrings','glutes','calves','core','full_body','cardio','other'];
export function validateExerciseProfile(input:ExerciseProfileInput){if(!input.name.trim())throw new Error('Exercise name is required.');if(!muscleGroups.includes(input.muscle_group))throw new Error('Choose a primary muscle group.');if(input.secondary_muscle_group===input.muscle_group)throw new Error('Choose a different secondary muscle group.');if(!Number.isFinite(input.default_sets)||input.default_sets<1||input.default_sets>10)throw new Error('Default sets must be between 1 and 10.');for(const[label,value]of[['Minimum weight',input.minimum_weight],['Maximum weight',input.maximum_weight],['Weight increment',input.increment_kg]]as const)if(value!==null&&(!Number.isFinite(value)||value<0))throw new Error(`${label} must be a valid amount.`);if(input.minimum_weight!==null&&input.maximum_weight!==null&&input.minimum_weight>input.maximum_weight)throw new Error('Minimum weight cannot exceed maximum weight.');if(input.available_weights.some(value=>!Number.isFinite(value)||value<0))throw new Error('Available weights must be valid positive values.');}
export async function loadExerciseProfiles(){const owner=await requireOwner(),[rows,history]=await Promise.all([supabase.from('training_exercises').select('*').eq('owner_id',owner).order('name'),supabase.from('training_exercise_configurations').select('exercise_id').eq('owner_id',owner)]);fail('Exercise Library',rows.error);fail('Exercise configuration history',history.error);return(rows.data??[]).map(row=>({...row,default_sets:Number(row.default_sets),min_target:row.min_target==null?null:Number(row.min_target),max_target:row.max_target==null?null:Number(row.max_target),increment_kg:Number(row.increment_kg),minimum_weight:row.minimum_weight==null?null:Number(row.minimum_weight),maximum_weight:row.maximum_weight==null?null:Number(row.maximum_weight),available_weights:(row.available_weights??[]).map(Number),historyCount:(history.data??[]).filter(item=>item.exercise_id===row.id).length}))as ExerciseProfile[]}
export async function saveExerciseProfile(input:ExerciseProfileInput,id?:string){validateExerciseProfile(input);const owner=await requireOwner(),payload={...input,name:input.name.trim(),muscle_group:input.muscle_group.trim(),secondary_muscle_group:input.secondary_muscle_group?.trim()||null,equipment:input.equipment?.trim()||null,notes:input.notes?.trim()||null,available_weights:[...new Set(input.available_weights)].sort((a,b)=>a-b),updated_at:new Date().toISOString()};if(id){const result=await supabase.from('training_exercises').update(payload).eq('id',id).eq('owner_id',owner).select('id').single();fail('Update exercise',result.error)}else{const result=await supabase.from('training_exercises').insert({...payload,owner_id:owner,exercise_key:`CUSTOM-${crypto.randomUUID()}`,active:true}).select('id').single();fail('Create exercise',result.error)}}
export async function setExerciseArchived(id:string,archived:boolean){const owner=await requireOwner(),result=await supabase.from('training_exercises').update({active:!archived,archived_at:archived?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',id).eq('owner_id',owner).select('id').single();fail(archived?'Archive exercise':'Restore exercise',result.error)}
export async function loadExerciseHistory(exerciseId:string){
  const owner=await requireOwner();
  const sessions=await supabase.from('training_sessions').select('id,performed_on,workout_type,variant').eq('owner_id',owner);
  fail('Exercise history',sessions.error);
  const sessionById=new Map((sessions.data??[]).map(row=>[row.id,row]));
  if(!sessionById.size)return[] as ExerciseHistoryItem[];
  const entries=await supabase.from('training_session_exercises').select('id,session_id,notes').eq('exercise_id',exerciseId).in('session_id',[...sessionById.keys()]);
  fail('Exercise history',entries.error);
  const sets=entries.data?.length?await supabase.from('training_sets').select('session_exercise_id,load_kg').in('session_exercise_id',entries.data.map(row=>row.id)):{data:[],error:null};
  fail('Exercise sets',sets.error);
  return(entries.data??[]).map(entry=>{const session=sessionById.get(entry.session_id),loads=(sets.data??[]).filter(set=>set.session_exercise_id===entry.id).map(set=>set.load_kg==null?null:Number(set.load_kg)).filter((value):value is number=>value!==null);return{id:entry.id,performedOn:session?.performed_on??'',workoutName:[session?.workout_type,session?.variant].filter(Boolean).join(' · ')||'Workout',sets:(sets.data??[]).filter(set=>set.session_exercise_id===entry.id).length,bestLoad:loads.length?Math.max(...loads):null,notes:entry.notes??null}}).sort((a,b)=>b.performedOn.localeCompare(a.performedOn)).slice(0,20) as ExerciseHistoryItem[];
}
