import{supabase}from'./supabase';
import{requireOwner}from'./trainingRepository';

const fail=(label:string,error:{message:string}|null)=>{if(error)throw new Error(`${label}: ${error.message}`)};
export type ResistanceType='machine'|'cable'|'dumbbell'|'barbell'|'plate_loaded'|'smith_machine'|'bodyweight'|'assisted_bodyweight'|'cardio_machine'|'other';
export type WeightConvention='total_weight'|'per_hand'|'per_side'|'bodyweight_only'|'bodyweight_added'|'bodyweight_assistance';
export type ExerciseProfile={id:string;exercise_key:string;name:string;muscle_group:string;secondary_muscle_group:string|null;equipment:string|null;resistance_type:ResistanceType|null;default_sets:number;min_target:number|null;max_target:number|null;increment_kg:number;minimum_weight:number|null;maximum_weight:number|null;available_weights:number[];weight_convention:WeightConvention|null;measurement_type:string;progression_type:string;notes:string|null;active:boolean;archived_at:string|null;historyCount:number};
export type ExerciseProfileInput=Omit<ExerciseProfile,'id'|'exercise_key'|'active'|'archived_at'|'historyCount'>;
export const resistanceTypes:ResistanceType[]=['machine','cable','dumbbell','barbell','plate_loaded','smith_machine','bodyweight','assisted_bodyweight','cardio_machine','other'];
export const weightConventions:WeightConvention[]=['total_weight','per_hand','per_side','bodyweight_only','bodyweight_added','bodyweight_assistance'];
export function validateExerciseProfile(input:ExerciseProfileInput){if(!input.name.trim())throw new Error('Exercise name is required.');if(!input.muscle_group.trim())throw new Error('Muscle group is required.');if(input.default_sets<1||input.default_sets>10)throw new Error('Default sets must be between 1 and 10.');for(const[label,value]of[['Minimum weight',input.minimum_weight],['Maximum weight',input.maximum_weight],['Weight increment',input.increment_kg]]as const)if(value!==null&&(!Number.isFinite(value)||value<0))throw new Error(`${label} cannot be negative.`);if(input.minimum_weight!==null&&input.maximum_weight!==null&&input.minimum_weight>input.maximum_weight)throw new Error('Minimum weight cannot exceed maximum weight.');if(input.available_weights.some(value=>!Number.isFinite(value)||value<0))throw new Error('Available weights must be valid positive values.');}
export async function loadExerciseProfiles(){const owner=await requireOwner(),[rows,history]=await Promise.all([supabase.from('training_exercises').select('*').eq('owner_id',owner).order('name'),supabase.from('training_exercise_configurations').select('exercise_id').eq('owner_id',owner)]);fail('Exercise Library',rows.error);fail('Exercise configuration history',history.error);return(rows.data??[]).map(row=>({...row,default_sets:Number(row.default_sets),min_target:row.min_target==null?null:Number(row.min_target),max_target:row.max_target==null?null:Number(row.max_target),increment_kg:Number(row.increment_kg),minimum_weight:row.minimum_weight==null?null:Number(row.minimum_weight),maximum_weight:row.maximum_weight==null?null:Number(row.maximum_weight),available_weights:(row.available_weights??[]).map(Number),historyCount:(history.data??[]).filter(item=>item.exercise_id===row.id).length}))as ExerciseProfile[]}
export async function saveExerciseProfile(input:ExerciseProfileInput,id?:string){validateExerciseProfile(input);const owner=await requireOwner(),payload={...input,name:input.name.trim(),muscle_group:input.muscle_group.trim(),secondary_muscle_group:input.secondary_muscle_group?.trim()||null,equipment:input.equipment?.trim()||null,notes:input.notes?.trim()||null,available_weights:[...new Set(input.available_weights)].sort((a,b)=>a-b),updated_at:new Date().toISOString()};if(id){const result=await supabase.from('training_exercises').update(payload).eq('id',id).eq('owner_id',owner).select('id').single();fail('Update exercise',result.error)}else{const result=await supabase.from('training_exercises').insert({...payload,owner_id:owner,exercise_key:`CUSTOM-${crypto.randomUUID()}`,active:true}).select('id').single();fail('Create exercise',result.error)}}
export async function setExerciseArchived(id:string,archived:boolean){const owner=await requireOwner(),result=await supabase.from('training_exercises').update({active:!archived,archived_at:archived?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',id).eq('owner_id',owner).select('id').single();fail(archived?'Archive exercise':'Restore exercise',result.error)}
