import{useEffect,useMemo,useState,type Dispatch,type PointerEvent,type SetStateAction}from'react';
import{ChevronLeft,ChevronRight,Grid3X3,X}from'lucide-react';
import{getForestAsset,type ForestAsset}from'./forestAssets';
import{forestEnvironmentManifest,forestTreeManifest}from'./forestManifest';
import{forestAssignmentDebug,forestAssignments,forestEnvironmentSlots,type ForestSlot}from'./forestLayout';
import{ForestTreeCard,ForestTreeLabels,ForestTreeLayer,useForestInteraction,useForestSceneAssets}from'./ForestSceneEngine';
import{ForestEnvironmentScene,useForestProjection}from'./ForestEnvironmentScene';
import{loadForestSlots,mergeForestSlotLayers,publishForestSlots,resetForestSlotsAcrossMiddle,saveForestSlotDraft,saveForestSlotsDraft}from'./forestComposerRepository';
import type{HomeGoal}from'./homeRepository';
import ForestTestPresets from'./ForestTestPresets';
import{loadTreeScale,loadTreeScales,publishTreeScale,saveTreeScaleDraft,type TreeScaleCalibration}from'./treeScaleRepository';

type Mode='tree'|'environment'|'composer'|'presets';
const environmentAssetKey=(key:string)=>`forest.environment.${key.startsWith('area-')?`area.${key.slice(5)}`:key.replaceAll('-','_')}`;

export default function ForestLabQA({close}:{close:()=>void}){
 const[mode,setMode]=useState<Mode>(import.meta.env.DEV&&new URLSearchParams(location.search).get('forest-qa')==='nursery'?'composer':'tree'),[stage,setStage]=useState(1),[environment,setEnvironment]=useState('clearing'),[asset,setAsset]=useState<ForestAsset|null>(),[error,setError]=useState(''),[contactSheet,setContactSheet]=useState(false),[scale,setScale]=useState(forestTreeManifest[0].defaultScale),[scaleNotice,setScaleNotice]=useState('');
 const tree=forestTreeManifest[stage-1],environmentName=forestEnvironmentManifest.find(([key])=>key===environment)?.[1]??environment,key=mode==='tree'?tree.assetKey:mode==='presets'?'forest.environment.clearing':environmentAssetKey(environment);
 useEffect(()=>{let current=true;setAsset(undefined);setError('');getForestAsset(key).then(value=>{if(!current)return;if(!value)setError('Production asset is not ready.');setAsset(value)}).catch(()=>current&&setError('Production asset could not be loaded.'));return()=>{current=false}},[key]);
 useEffect(()=>{if(asset?.asset_kind==='tree')setScale(asset.default_scale)},[asset]);
 const anchor=asset?.ground_anchor_y??tree?.groundAnchorY??1,treeStyle=useMemo(()=>asset?{'--tree-ground':`${anchor*100}%`,'--tree-scale':String(scale)}as React.CSSProperties:undefined,[asset,anchor,scale]);
 const scaleItem:TreeScaleCalibration={stage,canonical_visual_scale:scale,visual_height_class:tree.visualHeightClass,visual_footprint_class:tree.visualFootprintClass};
 const saveScale=async(state:'draft'|'published')=>{setScaleNotice(state==='draft'?'Saving draft…':'Publishing…');try{await(state==='draft'?saveTreeScaleDraft(scaleItem):publishTreeScale(scaleItem));setScaleNotice(state==='draft'?'Draft saved.':'Published scale is now live.')}catch(error){setScaleNotice(error instanceof Error?error.message:'Tree scale could not be saved.')}};
 const restoreScale=async()=>{const published=await loadTreeScale(stage);const next=published?.canonical_visual_scale??tree.defaultScale;setScale(next);setScaleNotice('Published scale restored.')};
 return <div className="forest-lab-qa"><header><div><p>AUTHORIZED QA</p><h1>Forest Lab</h1></div><div className="forest-lab-tabs">{(['tree','environment','composer','presets']as Mode[]).map(value=><button key={value} className={mode===value?'active':''} onClick={()=>{setMode(value);setContactSheet(false)}}>{value==='tree'?'Trees':value==='environment'?'Environments':value==='composer'?'Composer':'Test Presets'}</button>)}</div><button aria-label="Close Forest Lab" onClick={close}><X/></button></header><aside><p className="forest-lab-note">Production previews and calibration. Drafts do not affect production until published.</p>{mode==='tree'?<><label>Tree stage<select value={stage} onChange={event=>setStage(Number(event.target.value))}>{forestTreeManifest.map(item=><option value={item.stage} key={item.stage}>{String(item.stage).padStart(2,'0')} · {item.canonicalName}</option>)}</select></label><div className="forest-lab-step"><button disabled={stage===1} onClick={()=>setStage(value=>value-1)}><ChevronLeft/> Previous</button><button disabled={stage===27} onClick={()=>setStage(value=>value+1)}>Next <ChevronRight/></button></div><button className="forest-lab-sheet-button" onClick={()=>setContactSheet(value=>!value)}><Grid3X3/> {contactSheet?'Single Tree':'27-Tree contact sheet'}</button><dl><div><dt>Ground anchor</dt><dd>{Math.round(anchor*100)}%</dd></div><div><dt>Depth</dt><dd>{asset?.depth_preference??tree.depthPreference}</dd></div><div><dt>Source</dt><dd>{asset?.width??tree.width} × {asset?.height??tree.height}</dd></div></dl></>:mode==='environment'||mode==='composer'?<label>Environment<select value={environment} onChange={event=>setEnvironment(event.target.value)}>{forestEnvironmentManifest.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>:<p className="forest-lab-note">Apply isolated lifecycle, Area, stage and health states to Test Goals.</p>}</aside><main className={mode==='environment'?'environment-preview':''}>{error&&<div className="forest-asset-error">{error}</div>}{asset===undefined&&!error&&<div className="forest-asset-loading">Loading production asset…</div>}{mode==='tree'&&asset&&!contactSheet&&<div className="tree-calibration"><div className="tree-viewport" style={treeStyle}><img src={asset.url} alt={`${tree.canonicalName} production Tree`}/><i className="ground-mask"/><span className="ground-line">GROUND</span></div><div><strong>{String(stage).padStart(2,'0')} · {tree.canonicalName}</strong><small>{asset.storage_path}</small></div></div>}{mode==='tree'&&contactSheet&&<TreeContactSheet/>}{mode==='environment'&&asset&&<figure className="environment-master"><img src={asset.url} alt={`${environmentName} production environment`}/><figcaption><strong>{environmentName}</strong><small>{asset.storage_path}</small></figcaption></figure>}{mode==='composer'&&asset&&<EnvironmentComposer environment={environment} background={asset}/>} {mode==='presets'&&<ForestTestPresets/>}</main></div>;
}

const testGoals:HomeGoal[]=Array.from({length:5},(_,i)=>({id:`composer-test-${i+1}`,title:`Test Goal ${i+1}`,status:'active',presentation_priority:i<4?'primary':'secondary',area_key:'Health',created_at:'2026-09-03T00:00:00Z',starts_on:'2026-09-03',tree_stage:(i%3)+1,tree_species:['Seed','Sprout','Young Plant'][i%3],tree_asset_key:`forest.tree.stage0${(i%3)+1}`,forest_environment:'nursery',growth_consistency:80,health_state:'Healthy',contribution_count:i%3,eligible_days:3,nursery_label:['Seed','Sprout','Young Plant'][i%3],nursery_next:'QA fixture',nursery_progress:33*(i%3)}));

function EnvironmentComposer({environment,background}:{environment:string;background:ForestAsset}){
 const defaults=forestEnvironmentSlots[environment]??[],[slots,setSlots]=useState<ForestSlot[]>(()=>defaults.map(slot=>({...slot}))),[selectedId,setSelectedId]=useState(defaults[0]?.id??''),[notice,setNotice]=useState(''),[presentation,setPresentation]=useState<'full'|'hero'>('full'),[width,setWidth]=useState(1100);
 useEffect(()=>{let current=true;Promise.all([loadForestSlots(environment,'draft'),loadForestSlots(environment,'published')]).then(([draft,published])=>{if(!current)return;const next=mergeForestSlotLayers(defaults,published,draft);setSlots(next);setSelectedId(next[0]?.id??'')});return()=>{current=false}},[environment,defaults]);
 const assignments=useMemo(()=>forestAssignments(environment,testGoals,slots),[environment,slots]),selectedSlot=slots.find(slot=>slot.id===selectedId)??slots[0],{trees}=useForestSceneAssets(environmentAssetKey(environment),assignments),interaction=useForestInteraction(),selectedTree=assignments.find(item=>item.goal.id===interaction.active),audit=forestAssignmentDebug(environment,assignments);
 const update=(changes:Partial<ForestSlot>)=>selectedSlot&&updateSlot(setSlots,selectedSlot.id,changes),resetToMiddle=()=>{setSlots(items=>resetForestSlotsAcrossMiddle(items,5,environment));setNotice('Five anchors aligned across the middle. Save All Anchors or Publish to keep this arrangement.')},saveThis=async()=>{if(!selectedSlot)return;setNotice('Saving selected anchor…');try{await saveForestSlotDraft(environment,selectedSlot);setNotice(`${selectedSlot.id} saved as a draft.`)}catch(error){setNotice(error instanceof Error?error.message:'Anchor draft could not be saved.')}},saveAll=async()=>{setNotice('Saving all anchors…');try{await saveForestSlotsDraft(environment,slots);setNotice(`All ${slots.length} anchors saved as a draft.`)}catch(error){setNotice(error instanceof Error?error.message:'Draft could not be saved.')}},publish=async()=>{setNotice('Publishing…');try{await publishForestSlots(environment,slots);setNotice('Published calibration is now live.')}catch(error){setNotice(error instanceof Error?error.message:'Calibration could not be published.')}};
 return <div className="nursery-placement-qa forest-composer" style={{width:`min(${width}px,100%)`}}><div className={`composer-scene ${presentation}`}><ForestEnvironmentScene asset={background} overlay="linear-gradient(180deg,rgba(3,24,18,.08),rgba(3,24,18,.25))">{slots.map(slot=><DraggableSlot key={slot.id} slot={slot} selected={slot.id===selectedId} onSelect={()=>setSelectedId(slot.id)} onMove={(x,y)=>{setSelectedId(slot.id);updateSlot(setSlots,slot.id,{x,y})}}/>)}<div className="forest-world-layer"><ForestTreeLayer assignments={assignments} trees={trees} variant={presentation==='hero'?'hero':'overview'} environment={environment} onSelect={interaction.select} onHover={interaction.hover} onLeave={interaction.leave} debug/></div><div className="forest-interaction-layer"><ForestTreeLabels assignments={assignments} environment={environment} onSelect={interaction.select} onHover={interaction.hover} onLeave={interaction.leave}/>{selectedTree&&<ForestTreeCard assignment={selectedTree} variant={presentation==='hero'?'hero':'overview'} onClose={interaction.close} onViewGoal={()=>{}} onLog={()=>{}}/>}</div></ForestEnvironmentScene></div><div className="forest-composer-preview"><label>View<select value={presentation} onChange={e=>setPresentation(e.target.value as 'full'|'hero')}><option value="full">Full Forest</option><option value="hero">Home Hero</option></select></label><label>Preview width<input type="range" min="320" max="1440" value={width} onChange={e=>setWidth(Number(e.target.value))}/><span>{width}px</span></label><label>Slot<select value={selectedId} onChange={e=>setSelectedId(e.target.value)}>{slots.map(slot=><option key={slot.id}>{slot.id}</option>)}</select></label>{selectedSlot&&<SlotControls slot={selectedSlot} update={update}/>}<div><button onClick={resetToMiddle}>Reset Anchors to Middle</button><button onClick={saveThis}>Save This Anchor</button><button onClick={saveAll}>Save All Anchors</button><button onClick={publish}>Publish</button></div></div>{notice&&<p className="composer-notice">{notice}</p>}<div className="nursery-placement-report"><b>{assignments.length} eligible · {assignments.length} rendered · {new Set(assignments.map(item=>item.slot.id)).size} unique slots</b>{audit.map(row=><code key={row.goal_id}>{row.goal_id} → {row.slot_id} · ground ({(row.anchor_x*100).toFixed(1)}%, {(row.anchor_y*100).toFixed(1)}%) · environment ({(row.anchor_x*100).toFixed(1)}%, {(row.anchor_y*100).toFixed(1)}%)</code>)}</div></div>;
}

function SlotControls({slot,update}:{slot:ForestSlot;update:(changes:Partial<ForestSlot>)=>void}){return <><label>X<input type="number" min="0" max="1" step=".001" value={slot.x} onChange={e=>update({x:Number(e.target.value)})}/></label><label>Y<input type="number" min="0" max="1" step=".001" value={slot.y} onChange={e=>update({y:Number(e.target.value)})}/></label><label>Scale<input type="number" min=".1" max="3" step=".01" value={slot.scale} onChange={e=>update({scale:Number(e.target.value)})}/></label><label>Depth<select value={slot.depth} onChange={e=>update({depth:e.target.value as ForestSlot['depth']})}><option>far</option><option>mid</option><option>near</option></select></label><label>Label X<input type="number" step=".005" value={slot.labelAnchorX??0} onChange={e=>update({labelAnchorX:Number(e.target.value)})}/></label><label>Label Y<input type="number" step=".005" value={slot.labelAnchorY??.015} onChange={e=>update({labelAnchorY:Number(e.target.value)})}/></label><label>Card<select value={slot.preferredCardDirection??'auto'} onChange={e=>update({preferredCardDirection:e.target.value as ForestSlot['preferredCardDirection']})}><option>auto</option><option>left</option><option>right</option><option>above</option><option>below</option></select></label><label>Enabled<input type="checkbox" checked={slot.enabled!==false} onChange={e=>update({enabled:e.target.checked})}/></label></>}
function updateSlot(setSlots:Dispatch<SetStateAction<ForestSlot[]>>,id:string,changes:Partial<ForestSlot>){setSlots(items=>items.map(slot=>slot.id===id?{...slot,...changes}:slot))}
function DraggableSlot({slot,selected,onSelect,onMove}:{slot:ForestSlot;selected:boolean;onSelect:()=>void;onMove:(x:number,y:number)=>void}){const{project,unproject}=useForestProjection(),point=project(slot);const move=(event:PointerEvent<HTMLButtonElement>)=>{if(!event.currentTarget.hasPointerCapture(event.pointerId))return;const scene=event.currentTarget.closest('.forest-environment-scene')!.getBoundingClientRect(),next=unproject({x:event.clientX-scene.left,y:event.clientY-scene.top});onMove(next.x,next.y)};return <button type="button" className={`composer-slot-marker ${selected?'selected':''}`} style={{left:point.x,top:point.y}} onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);onSelect()}} onPointerMove={move} aria-label={`Move ${slot.id}`}><i/><b>{slot.id}</b><small>LABEL</small></button>}
function TreeContactSheet(){
 const[assets,setAssets]=useState<Record<string,ForestAsset|null>>({}),[drafts,setDrafts]=useState<Record<number,TreeScaleCalibration>>({}),[selected,setSelected]=useState(1),[draftScale,setDraftScale]=useState(forestTreeManifest[0].defaultScale),[notice,setNotice]=useState('');
 const refresh=()=>Promise.all(forestTreeManifest.map(item=>getForestAsset(item.assetKey))).then(rows=>setAssets(Object.fromEntries(rows.map((asset,index)=>[forestTreeManifest[index].assetKey,asset]))));
 useEffect(()=>{let current=true;Promise.all([Promise.all(forestTreeManifest.map(item=>getForestAsset(item.assetKey))),loadTreeScales('draft')]).then(([rows,savedDrafts])=>{if(!current)return;setAssets(Object.fromEntries(rows.map((asset,index)=>[forestTreeManifest[index].assetKey,asset])));setDrafts(Object.fromEntries(savedDrafts.map(draft=>[draft.stage,draft])))});return()=>{current=false}},[]);
 useEffect(()=>{const item=forestTreeManifest[selected-1],asset=assets[item.assetKey];setDraftScale(drafts[selected]?.canonical_visual_scale??asset?.default_scale??item.defaultScale)},[selected,assets,drafts]);
 const item=forestTreeManifest[selected-1],calibration:TreeScaleCalibration={stage:selected,canonical_visual_scale:draftScale,visual_height_class:item.visualHeightClass,visual_footprint_class:item.visualFootprintClass};
 const save=async(state:'draft'|'published')=>{setNotice(state==='draft'?'Saving…':'Publishing…');try{await(state==='draft'?saveTreeScaleDraft(calibration):publishTreeScale(calibration));if(state==='draft')setDrafts(items=>({...items,[selected]:calibration}));else await refresh();setNotice(state==='draft'?'Draft saved.':'Published scale is now live.')}catch(error){setNotice(error instanceof Error?error.message:'Tree scale could not be saved.')}};
 const restore=async()=>{const published=await loadTreeScale(selected);setDraftScale(published?.canonical_visual_scale??item.defaultScale);setNotice('Published scale restored.')};
 return <div className="tree-scale-lab"><div className="tree-contact-sheet">{forestTreeManifest.map(entry=>{const asset=assets[entry.assetKey],shownScale=entry.stage===selected?draftScale:(drafts[entry.stage]?.canonical_visual_scale??asset?.default_scale??entry.defaultScale);return <article key={entry.assetKey} role="button" tabIndex={0} aria-pressed={selected===entry.stage} className={selected===entry.stage?'selected':''} onClick={()=>setSelected(entry.stage)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setSelected(entry.stage)}}}><div style={{'--contact-anchor':`${(asset?.ground_anchor_y??entry.groundAnchorY)*100}%`,'--contact-scale':String(shownScale)}as React.CSSProperties}>{asset?<img src={asset.url} alt=""/>:<span/>}<i/></div><b>{String(entry.stage).padStart(2,'0')}</b><small>{entry.canonicalName}</small><em>{shownScale.toFixed(2)}</em></article>})}</div><aside className="tree-scale-editor"><strong>{String(selected).padStart(2,'0')} · {item.canonicalName}</strong><small>{item.visualHeightClass.replaceAll('_',' ')} · {item.visualFootprintClass}</small><label>Canonical visual scale<input type="range" min=".02" max="1.5" step=".01" value={draftScale} onChange={event=>setDraftScale(Number(event.target.value))}/><span>{draftScale.toFixed(2)}</span></label><div><button onClick={()=>save('draft')}>Save Draft</button><button onClick={()=>save('published')}>Publish</button><button onClick={restore}>Restore Published</button></div>{notice&&<p>{notice}</p>}</aside></div>}
