import {useEffect,useMemo,useState,type CSSProperties} from 'react';
import {ChevronLeft,Plus,X} from 'lucide-react';
import {getForestAsset,type ForestAsset} from './forestAssets';
import {forestEnvironmentManifest} from './forestManifest';
import {stablePlacementSeed} from './domain';
import {loadHome,type HomeGoal} from './homeRepository';

const slots=[{x:15,y:76,scale:.88},{x:32,y:69,scale:.68},{x:50,y:77,scale:1},{x:68,y:68,scale:.66},{x:85,y:75,scale:.84}] as const;
const assetKey=(key:string)=>'forest.environment.'+(key.startsWith('area-')?'area.'+key.slice(5):key.replaceAll('-','_'));

export default function ForestOverview({close,onViewGoals,onLog}:{close:()=>void;onViewGoals:()=>void;onLog:()=>void}){
  const [goals,setGoals]=useState<HomeGoal[]>([]),[environment,setEnvironment]=useState('clearing'),[background,setBackground]=useState<ForestAsset|null>(),[trees,setTrees]=useState<Record<string,ForestAsset>>({}),[selected,setSelected]=useState<string>(),[error,setError]=useState('');
  useEffect(()=>{loadHome().then(data=>setGoals(data.goals)).catch(()=>setError('Your Forest could not be loaded.'))},[]);
  const visible=useMemo(()=>{if(environment==='clearing')return goals.filter(goal=>goal.status==='active'&&goal.presentation_priority==='primary'&&goal.tree_stage>=4).slice(0,4);if(environment==='nursery')return goals.filter(goal=>goal.status==='active'&&goal.tree_stage<=3);if(environment==='dormant-woods')return goals.filter(goal=>goal.status==='dormant');if(environment==='heartwood')return goals.filter(goal=>goal.status==='completed');const area=environment.replace('area-','');return goals.filter(goal=>goal.status==='active'&&goal.tree_stage>=4&&goal.area_key.toLowerCase()===area)},[environment,goals]);
  useEffect(()=>{let current=true;setSelected(undefined);Promise.all([getForestAsset(assetKey(environment)),...visible.slice(0,5).map(goal=>getForestAsset(goal.tree_asset_key))]).then(([scene,...assets])=>{if(!current)return;setBackground(scene);setTrees(Object.fromEntries(visible.slice(0,5).flatMap((goal,index)=>assets[index]?[[goal.id,assets[index] as ForestAsset]]:[])))});return()=>{current=false}},[environment,visible.map(goal=>goal.id+':'+goal.tree_stage).join('|')]);
  const selectedGoal=visible.find(goal=>goal.id===selected),label=forestEnvironmentManifest.find(([key])=>key===environment)?.[1]??environment;
  return <div className="forest-overview-shade" role="dialog" aria-modal="true" aria-label="Forest Overview"><section className="forest-overview"><header><button onClick={close} aria-label="Close Forest Overview"><ChevronLeft/></button><div><span>MY FOREST</span><h1>{label}</h1></div><button onClick={close} aria-label="Close"><X/></button></header><nav aria-label="Forest environments">{forestEnvironmentManifest.map(([key,name])=><button key={key} className={environment===key?'active':''} onClick={()=>setEnvironment(key)}>{name}</button>)}</nav><div className="forest-overview-scene" style={background?{backgroundImage:'linear-gradient(180deg,rgba(3,24,18,.12),rgba(3,24,18,.42)),url("'+background.url+'")'}:undefined}><div className="forest-overview-status"><b>{visible.length}</b><span>{visible.length===1?'Goal Tree':'Goal Trees'}</span></div>{error&&<div className="forest-overview-empty"><h2>{error}</h2></div>}{!error&&visible.length===0&&<div className="forest-overview-empty"><h2>{environment==='nursery'?'No new Goal Trees':'This part of your Forest is quiet.'}</h2><button onClick={onViewGoals}>{environment==='nursery'?'Plant a Goal':'View Goals'}</button></div>}{visible.slice(0,5).map((goal,index)=>{const asset=trees[goal.id],slot=slots[(stablePlacementSeed(goal.id)+index)%slots.length];if(!asset)return null;return <button className={'forest-overview-tree '+goal.health_state.toLowerCase().replaceAll(' ','-')} key={goal.id} onClick={()=>setSelected(goal.id)} style={{left:slot.x+'%',top:slot.y+'%','--tree-scale':String(slot.scale*asset.default_scale),'--ground-anchor':String(asset.ground_anchor_y),'--z':String(Math.round(slot.y+asset.z_bias))} as CSSProperties}><span><img src={asset.url} alt=""/><i/></span><label>{goal.title}<small>{goal.tree_species}</small></label></button>})}{visible.length>5&&<span className="forest-more-trees">+{visible.length-5} more Trees</span>}{selectedGoal&&<article className="forest-overview-card"><button aria-label="Close Tree details" onClick={()=>setSelected(undefined)}><X/></button><span>{selectedGoal.area_key.toUpperCase()}</span><h2>{selectedGoal.title}</h2><p>{selectedGoal.tree_species} · {selectedGoal.health_state}</p><small>{Math.round(selectedGoal.growth_consistency)}% Growth Consistency</small><div><button onClick={onViewGoals}>View Goal</button><button onClick={onLog}><Plus/> Log</button></div></article>}</div></section></div>;
}
