import{useState}from'react';import{Activity,Bike,BookOpen,Brain,CircleDollarSign,Dumbbell,Footprints,HeartPulse,Moon,Music2,Pill,Scale,Sparkles,Utensils,Waves,X,type LucideIcon}from'lucide-react';
import type{ModuleKey}from'./modules';
import type{MeasurementType}from'./goalsDomain';

export const functionalIconKeys=['habit','metric','activity','weight','strength','running','walking','cycling','swimming','meditation','reading','music','sleep','nutrition','money','supplement','recovery','hobby']as const;
export type FunctionalIconKey=typeof functionalIconKeys[number];
const icons:Record<FunctionalIconKey,{label:string;Icon:LucideIcon}>={habit:{label:'Habit',Icon:Sparkles},metric:{label:'Measurement',Icon:Activity},activity:{label:'Activity',Icon:Activity},weight:{label:'Weight',Icon:Scale},strength:{label:'Strength',Icon:Dumbbell},running:{label:'Running',Icon:Activity},walking:{label:'Walking',Icon:Footprints},cycling:{label:'Cycling',Icon:Bike},swimming:{label:'Swimming',Icon:Waves},meditation:{label:'Meditation',Icon:Brain},reading:{label:'Reading',Icon:BookOpen},music:{label:'Music',Icon:Music2},sleep:{label:'Sleep',Icon:Moon},nutrition:{label:'Nutrition',Icon:Utensils},money:{label:'Money',Icon:CircleDollarSign},supplement:{label:'Supplement',Icon:Pill},recovery:{label:'Recovery',Icon:HeartPulse},hobby:{label:'Hobby',Icon:Sparkles}};
export function suggestFunctionalIcon(name:string,module?:ModuleKey,measurement?:MeasurementType):FunctionalIconKey{const value=name.toLowerCase();if(/walk|step/.test(value))return'walking';if(/run|jog/.test(value))return'running';if(/cycle|bike|bicycle/.test(value))return'cycling';if(/swim/.test(value))return'swimming';if(/gym|strength|lift|weight training/.test(value))return'strength';if(/meditat|mindful|breath/.test(value))return'meditation';if(/read|book/.test(value))return'reading';if(/piano|music|guitar|sing/.test(value))return'music';if(/sleep|bedtime/.test(value)||module==='sleep')return'sleep';if(/food|meal|nutrition/.test(value)||module==='nutrition')return'nutrition';if(module==='money'||measurement==='money')return'money';if(/supplement|vitamin|creatine|medication|medicine|tablet|capsule/.test(value)||module==='medication')return'supplement';if(/weight|weigh/.test(value)||measurement==='weight')return'weight';if(module==='training')return'strength';if(module==='activity')return'activity';if(module==='hobbies')return'hobby';if(module==='habits')return'habit';return'metric'}
export function FunctionalIcon({iconKey='metric',size='standard'}:{iconKey?:string|null;size?:'small'|'standard'|'large'}){const entry=icons[iconKey as FunctionalIconKey]??icons.metric;return <span className={`functional-icon functional-icon-${size}`} aria-hidden="true"><entry.Icon/></span>}
export function FunctionalIconPicker({value,onChange}:{value:FunctionalIconKey;onChange:(value:FunctionalIconKey)=>void}){const[open,setOpen]=useState(false);return <div className="functional-icon-field"><span>Icon</span><button type="button" onClick={()=>setOpen(true)}><FunctionalIcon iconKey={value}/><b>{icons[value].label}</b><small>Change</small></button>{open&&<div className="functional-icon-shade" onMouseDown={()=>setOpen(false)}><section role="dialog" aria-modal="true" aria-label="Choose an icon" onMouseDown={event=>event.stopPropagation()}><header><h3>Choose an icon</h3><button type="button" aria-label="Close icon picker" onClick={()=>setOpen(false)}><X/></button></header><div>{functionalIconKeys.map(key=><button type="button" className={value===key?'active':''} onClick={()=>{onChange(key);setOpen(false)}} key={key}><FunctionalIcon iconKey={key}/><span>{icons[key].label}</span></button>)}</div></section></div>}</div>}
