import {useEffect,useState} from 'react';
import {Archive,Check,Layers3,Plus,X} from 'lucide-react';
import type {GoalBundle} from './goalsRepository';
import {archiveGrove,listGroves,saveGrove,type Grove,type GroveRole,type GroveStatus,type GroveType} from './grovesRepository';

const today=()=>new Date().toISOString().slice(0,10);
function GroveEditor({goals,grove,close,saved}:{goals:GoalBundle[];grove?:Grove;close:()=>void;saved:()=>void}){
  const[name,setName]=useState(grove?.name??''),[description,setDescription]=useState(grove?.description??''),[type,setType]=useState<GroveType>(grove?.grove_type??'ongoing'),[starts,setStarts]=useState(grove?.starts_on??today()),[ends,setEnds]=useState(grove?.ends_on??''),[members,setMembers]=useState<Record<string,GroveRole>>(()=>Object.fromEntries((grove?.members??[]).map(member=>[member.goal_id,member.membership_role]))),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const valid=Boolean(name.trim()&&starts&&(type==='ongoing'||ends)&&(!ends||ends>=starts)&&(type==='ongoing'||Object.values(members).includes('core')));
  return <div className="sheet-shade" onMouseDown={close}><section className="grove-editor" onMouseDown={event=>event.stopPropagation()}><button className="sheet-close" onClick={close}><X/></button><p className="eyebrow">{grove?'EDIT':'CREATE'} GROVE</p><h2>Bring related Goals together.</h2><p>A Grove organises actual Goals. It never duplicates or relocates their Trees.</p><div className="grove-form"><label>Name<input autoFocus value={name} onChange={event=>setName(event.target.value)}/></label><label>Description<textarea value={description} onChange={event=>setDescription(event.target.value)} placeholder="Optional context"/></label><label>Type<select value={type} onChange={event=>{const next=event.target.value as GroveType;setType(next);if(next==='ongoing')setEnds('')}}><option value="ongoing">Ongoing</option><option value="finite">Finite</option></select></label><label>Starts<input type="date" value={starts} onChange={event=>setStarts(event.target.value)}/></label>{type==='finite'&&<label>Ends<input type="date" min={starts} value={ends} onChange={event=>setEnds(event.target.value)}/></label>}</div><section className="grove-members"><h3>Goals</h3><p>{type==='finite'?'Core Goals determine completion. Supporting Goals never block it.':'Choose any related Goals. Roles remain useful context.'}</p>{goals.map(goal=>{const role=members[goal.id];return <div key={goal.id}><label><input type="checkbox" checked={Boolean(role)} onChange={event=>{const next={...members};if(event.target.checked)next[goal.id]='core';else delete next[goal.id];setMembers(next)}}/><span><b>{goal.title}</b><small>{goal.status} · {goal.presentation_priority}</small></span></label>{role&&<select value={role} onChange={event=>setMembers({...members,[goal.id]:event.target.value as GroveRole})}><option value="core">Core Goal</option><option value="supporting">Supporting Goal</option></select>}</div>})}{!goals.length&&<p>Plant a Goal before creating a Grove.</p>}</section>{!valid&&<p className="grove-hint">A name and start date are required. Finite Groves also need an end date and at least one Core Goal.</p>}{error&&<p className="goal-error">{error}</p>}<button className="save-record" disabled={!valid||busy} onClick={async()=>{setBusy(true);setError('');try{await saveGrove({name,description,groveType:type,startsOn:starts,endsOn:ends||null,members:Object.entries(members).map(([goalId,role])=>({goalId,role}))},grove?.id);saved()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save Grove')}finally{setBusy(false)}}}>{busy?'Saving…':'Save Grove'}</button></section></div>;
}

export default function GrovesPanel({goals}:{goals:GoalBundle[]}){
  const[groves,setGroves]=useState<Grove[]>([]),[filter,setFilter]=useState<GroveStatus>('active'),[editing,setEditing]=useState<Grove|null|undefined>(),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=()=>{setLoading(true);listGroves().then(setGroves).catch(reason=>setError(reason instanceof Error?reason.message:'Unable to load Groves')).finally(()=>setLoading(false))};
  useEffect(()=>{load()},[]);
  const visible=groves.filter(grove=>grove.status===filter);
  if(loading)return <div className="grove-loading">Loading Groves…</div>;
  return <section className="groves-panel"><div className="grove-tools"><div className="goal-tabs">{(['active','completed','archived'] as const).map(status=><button className={filter===status?'active':''} onClick={()=>setFilter(status)} key={status}>{status}</button>)}</div><button className="soft-button" onClick={()=>setEditing(null)}><Plus/> Create Grove</button></div>{error&&<p className="goal-error">{error}</p>}<div className="grove-list">{visible.map(grove=>{const core=grove.members.filter(member=>member.membership_role==='core'),done=core.filter(member=>member.goal.status==='completed').length;return <article key={grove.id}><div className="grove-icon">{grove.status==='completed'?<Check/>:<Layers3/>}</div><div><span>{grove.grove_type} GROVE · {grove.status}</span><h2>{grove.name}</h2>{grove.description&&<p>{grove.description}</p>}<small>{grove.starts_on}{grove.ends_on?` → ${grove.ends_on}`:' · no end date'}</small><div className="grove-goals">{grove.members.map(member=><span key={member.id}><b>{member.goal.title}</b><small>{member.membership_role} · {member.goal.status}</small></span>)}</div>{grove.grove_type==='finite'&&<strong>{done} of {core.length} Core Goals completed</strong>}</div><div className="grove-actions">{grove.status==='active'&&<button onClick={()=>setEditing(grove)}>Edit</button>}{grove.status!=='archived'&&<button onClick={()=>confirm('Archive this Grove? Its Goals will not change.')&&archiveGrove(grove.id).then(load).catch(reason=>setError(reason.message))}><Archive/> Archive</button>}</div></article>})}{!visible.length&&<div className="empty-state"><Layers3/><h2>No {filter} Groves</h2><p>Groves organise related Goals without changing their individual identity.</p></div>}</div>{editing!==undefined&&<GroveEditor goals={goals.filter(goal=>goal.status!=='archived')} grove={editing??undefined} close={()=>setEditing(undefined)} saved={()=>{setEditing(undefined);load()}}/>}</section>;
}
