export type GuidanceFeature='home'|'log'|'goals'|'groves'|'forest'|'tree_guide'|'climate'|'current_clearing'|'history'|'reviews'|'training'|'nutrition'|'money'|'account'|'canopy'|'cycle'|'plant_together';
export type GuidanceDefinition={featureKey:GuidanceFeature;version:number;title:string;intro:string;help:string;enabled:boolean;suggestionsKey?:string};
export type GuidanceSuggestion={key:string;title:string;detail:string;defaults:Record<string,string|number|boolean>};

export const guidanceRegistry:Record<GuidanceFeature,GuidanceDefinition>={
 home:{featureKey:'home',version:1,title:'Your day, in one place',intro:'See what matters today and log what happens without leaving Home.',help:'Home brings together Today, your Current Climate, Current Clearing and live Forest state.',enabled:true},
 log:{featureKey:'log',version:1,title:'Log what happened',intro:'Choose something you already configured, then record it in seconds.',help:'Log records an entry. Use Add & Manage when you want to create or configure something new.',enabled:true},
 goals:{featureKey:'goals',version:1,title:'Plant something to grow',intro:'Each Goal has one Tree for life. Its Area, progress and history stay with it.',help:'Goals describe what you want to grow. Primary and Secondary control presentation, not what must appear Today.',enabled:true,suggestionsKey:'goals'},
 groves:{featureKey:'groves',version:1,title:'Bring related Goals together',intro:'Goals keep their own Tree, Area, progress and history. A Grove simply organises what belongs together.',help:'A Goal can belong to more than one Grove. Removing it from a Grove never deletes the Goal or Tree.',enabled:true,suggestionsKey:'groves'},
 forest:{featureKey:'forest',version:1,title:'Your Goals grow here',intro:'Each Goal has one Tree for life. The Forest reflects the real state of what you are growing.',help:'New Trees begin in the Nursery, active Trees live in their Area, dormant Trees rest in Dormant Woods and completed Trees remain in Heartwood.',enabled:true},
 tree_guide:{featureKey:'tree_guide',version:1,title:'Follow a Tree through its life',intro:'Tree Levels reflect eligible Goal growth. The same Tree identity remains through every stage.',help:'The Tree Guide shows the canonical 27-stage growth ladder and the progress required for your selected Goal.',enabled:true},
 climate:{featureKey:'climate',version:1,title:'Set your Current Climate',intro:'Climate reflects the circumstances around you and can adjust expectations without rewriting your Goals.',help:'Normal is the default. A different Climate can temporarily adapt selected Goal expectations.',enabled:true},
 current_clearing:{featureKey:'current_clearing',version:1,title:'Focus without losing the wider Forest',intro:'A Current Clearing gives selected Goals temporary emphasis while every Goal keeps its identity.',help:'Use a Clearing for a focused period. It changes emphasis, not the underlying Goal or Tree.',enabled:true},
 history:{featureKey:'history',version:1,title:'Your complete record',intro:'History brings canonical records together so you can inspect, correct or delete the right entry.',help:'One real-world fact appears once in History even when it contributes to several Goals.',enabled:true},
 reviews:{featureKey:'reviews',version:1,title:'Look back with context',intro:'Reviews turn your recorded facts into a useful reflection without changing the original records.',help:'Correct the underlying record when something is wrong; Review summaries then update from canonical data.',enabled:true},
 training:{featureKey:'training',version:1,title:'Library, Templates and Sessions',intro:'The Exercise Library defines movements, Templates organise workouts, and Sessions record what you performed.',help:'Exercise identity and your personal setup stay separate so history and progression remain reliable.',enabled:true,suggestionsKey:'training'},
 nutrition:{featureKey:'nutrition',version:1,title:'Log meals once',intro:'Meal entries build the daily totals automatically. Saved Meals make repeated food faster to record.',help:'Food records remain individually editable while daily calories and macros are derived from them.',enabled:true,suggestionsKey:'nutrition'},
 money:{featureKey:'money',version:1,title:'Understand your Money',intro:'Accounts hold balances; transactions record income, spending, transfers and adjustments.',help:'Daily Money actions stay on the surface. Accounts, Categories and Recurring items live under Manage.',enabled:true,suggestionsKey:'money'},
 account:{featureKey:'account',version:1,title:'Your Fovyn settings',intro:'Manage your profile, preferences, Climate and other personal settings here.',help:'Your private account information is used to personalise Fovyn and is not your relational identity.',enabled:true},
 canopy:{featureKey:'canopy',version:1,title:'The Canopy',intro:'Connect through deliberate, permission-based support when Canopy Beta becomes available.',help:'Sharing and social actions remain explicit and privacy-controlled.',enabled:false},
 cycle:{featureKey:'cycle',version:1,title:'Private Cycle tracking',intro:'Cycle tracking is optional and private by default. Predictions are estimates, not contraception guidance.',help:'Choose what to record. Nothing is shared automatically or used to alter Training or Nutrition targets.',enabled:false,suggestionsKey:'cycle'},
 plant_together:{featureKey:'plant_together',version:1,title:'Plant Together',intro:'Create a shared commitment without merging either person’s private Forest or history.',help:'Participation and sharing remain explicit and revocable.',enabled:false},
};

export const suggestionRegistry:Record<string,GuidanceSuggestion[]>={
 goals:[{key:'exercise_3_weekly',title:'Exercise 3× weekly',detail:'A Health Goal with a weekly minimum.',defaults:{area_key:'health',rule_type:'at_least',target:3,unit:'sessions',period:'week'}}],
 groves:[{key:'wellbeing',title:'Wellbeing',detail:'Bring related Health and Mind Goals together.',defaults:{name:'Wellbeing'}}],
 training:[{key:'strength_session',title:'Strength session',detail:'Start a reusable strength workout Template.',defaults:{workout_type:'Strength'}}],
 nutrition:[{key:'usual_breakfast',title:'Usual breakfast',detail:'Create a reusable Saved Meal.',defaults:{meal_type:'breakfast',kind:'saved_meal'}}],
 money:[{key:'monthly_bills',title:'Monthly bills',detail:'Create a common recurring expense.',defaults:{transaction_type:'expense',recurrence:'monthly'}}],
 cycle:[{key:'common_symptoms',title:'Common symptoms',detail:'Choose only the symptoms useful to you.',defaults:{enabled:true}}],
};
