import {supabase} from './supabase';import{goalOwner}from'./goalsRepository';
const fail=(label:string,error:{message:string}|null)=>{if(error)throw new Error(`${label}: ${error.message}`)};
export type Macros={calories:number;protein_g:number;carbs_g:number;fat_g:number;fibre_g:number};
export type NutritionItem=Macros&{id:string;kind:'food'|'saved_meal';name:string;healthy:boolean|null};
export type NutritionEntry=Macros&{id:string;source_item_id:string|null;entry_kind:'food'|'saved_meal'|'manual_macros'|'meal_plan';name:string;meal_type:'breakfast'|'lunch'|'dinner'|'snack'|'custom';custom_meal:string|null;healthy:boolean|null;occurred_at:string;notes:string|null;corrected_at:string|null;goalIds:string[]};
export type NutritionTarget={id:string;nutrient:keyof Macros;target_type:'fixed'|'range'|'minimum'|'maximum';minimum_value:number|null;maximum_value:number|null};
export type NutritionData={items:NutritionItem[];entries:NutritionEntry[];targets:NutritionTarget[];goals:{id:string;title:string}[]};
export type EntryInput=Macros&{sourceItemId:string|null;entryKind:NutritionEntry['entry_kind'];name:string;mealType:NutritionEntry['meal_type'];customMeal:string;healthy:boolean|null;occurredAt:string;notes:string;goalIds:string[]};
export const zeroMacros=():Macros=>({calories:0,protein_g:0,carbs_g:0,fat_g:0,fibre_g:0});
export function validateMacros(input:Macros){for(const[key,value]of Object.entries(input))if(!Number.isFinite(value)||value<0)throw new Error(`${key.replace('_g','')} cannot be negative.`)}
export async function loadNutrition():Promise<NutritionData>{const user=await goalOwner();const[i,e,t,g,l]=await Promise.all([supabase.from('nutrition_items').select('id,kind,name,calories,protein_g,carbs_g,fat_g,fibre_g,healthy').eq('owner_id',user.id).is('archived_at',null).order('name'),supabase.from('nutrition_entries').select('id,source_item_id,entry_kind,name,meal_type,custom_meal,calories,protein_g,carbs_g,fat_g,fibre_g,healthy,occurred_at,notes,corrected_at').eq('owner_id',user.id).is('deleted_at',null).order('occurred_at',{ascending:false}).limit(300),supabase.from('nutrition_targets').select('id,nutrient,target_type,minimum_value,maximum_value').eq('owner_id',user.id),supabase.from('goals').select('id,title').eq('owner_id',user.id).in('status',['active','dormant']).order('title'),supabase.from('nutrition_entry_goals').select('nutrition_entry_id,goal_id').eq('owner_id',user.id)]);fail('Nutrition items',i.error);fail('Nutrition entries',e.error);fail('Nutrition targets',t.error);fail('Nutrition Goals',g.error);fail('Nutrition Goal links',l.error);return{items:(i.data??[])as NutritionItem[],entries:(e.data??[]).map(x=>({...x,goalIds:(l.data??[]).filter(y=>y.nutrition_entry_id===x.id).map(y=>y.goal_id)}))as NutritionEntry[],targets:(t.data??[])as NutritionTarget[],goals:(g.data??[])as{id:string;title:string}[]}}
export async function saveItem(input:Omit<NutritionItem,'id'>,id?:string){validateMacros(input);if(!input.name.trim())throw new Error('Name is required.');const user=await goalOwner(),payload={...input,name:input.name.trim(),owner_id:user.id,updated_at:new Date().toISOString()};const r=id?await supabase.from('nutrition_items').update(payload).eq('id',id).eq('owner_id',user.id).select('id').single():await supabase.from('nutrition_items').insert(payload).select('id').single();fail('Save nutrition item',r.error)}
export async function archiveItem(id:string){const user=await goalOwner();fail('Archive nutrition item',(await supabase.from('nutrition_items').update({archived_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('owner_id',user.id)).error)}
export async function saveEntry(input:EntryInput,id?:string){validateMacros(input);if(!input.name.trim())throw new Error('Name is required.');const user=await goalOwner(),payload={owner_id:user.id,source_item_id:input.sourceItemId,entry_kind:input.entryKind,name:input.name.trim(),meal_type:input.mealType,custom_meal:input.mealType==='custom'?input.customMeal.trim()||null:null,calories:input.calories,protein_g:input.protein_g,carbs_g:input.carbs_g,fat_g:input.fat_g,fibre_g:input.fibre_g,healthy:input.healthy,occurred_at:new Date(input.occurredAt).toISOString(),notes:input.notes.trim()||null,updated_at:new Date().toISOString(),...(id?{corrected_at:new Date().toISOString()}:{})};let entryId=id;if(id){const r=await supabase.from('nutrition_entries').update(payload).eq('id',id).eq('owner_id',user.id).is('deleted_at',null).select('id').single();fail('Correct nutrition entry',r.error)}else{const r=await supabase.from('nutrition_entries').insert(payload).select('id').single();fail('Log nutrition',r.error);entryId=r.data?.id}if(!entryId)throw new Error('Nutrition entry was not saved.');fail('Replace Nutrition Goal links',(await supabase.from('nutrition_entry_goals').delete().eq('nutrition_entry_id',entryId).eq('owner_id',user.id)).error);if(input.goalIds.length)fail('Link Nutrition Goals',(await supabase.from('nutrition_entry_goals').insert(input.goalIds.map(goal_id=>({nutrition_entry_id:entryId,goal_id,owner_id:user.id})))).error)}
export async function removeEntry(id:string){const user=await goalOwner();fail('Remove nutrition entry',(await supabase.from('nutrition_entries').update({deleted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('owner_id',user.id)).error)}
export async function saveTarget(input:Omit<NutritionTarget,'id'>){const user=await goalOwner(),min=input.target_type==='maximum'?null:input.minimum_value,max=input.target_type==='minimum'?null:input.target_type==='fixed'?input.minimum_value:input.maximum_value;if((min!=null&&min<0)||(max!=null&&max<0))throw new Error('Targets cannot be negative.');const r=await supabase.from('nutrition_targets').upsert({owner_id:user.id,nutrient:input.nutrient,target_type:input.target_type,minimum_value:min,maximum_value:max,updated_at:new Date().toISOString()},{onConflict:'owner_id,nutrient'});fail('Save nutrition target',r.error)}
export async function removeTarget(nutrient:keyof Macros){const user=await goalOwner();fail('Remove nutrition target',(await supabase.from('nutrition_targets').delete().eq('owner_id',user.id).eq('nutrient',nutrient)).error)}
