import {supabase} from './supabase';
import {goalOwner,type AreaRow,type SubcategoryRow,type UnitRow} from './goalsRepository';
import type {MeasurementType} from './goalsDomain';
import type {ModuleKey} from './modules';
import type{FunctionalIconKey}from'./functionalIcons';
import{fovynDateKey}from'./fovynDate';
const fail=(label:string,error:{message:string}|null)=>{if(error)throw new Error(`${label}: ${error.message}`)};
export type TrackerStatus='active'|'paused'|'archived';
export type Schedule={id:string;frequency_type:'anytime'|'daily'|'specific_days'|'times_per_week';days_of_week:number[];times_per_week:number|null;daypart:'morning'|'day'|'evening'|null;specific_time:string|null;effective_from:string;effective_to:string|null};
export type Tracker={id:string;name:string;module:ModuleKey;icon_key:FunctionalIconKey;area_key:string;subcategory_id:string|null;measurement_type:MeasurementType;unit_key:string|null;custom_unit:string|null;status:TrackerStatus;created_at:string;schedule:Schedule|null;recordCount:number;recentCount:number;lastRecordedAt:string|null;recordDates:string[];relatedGoals:{id:string;title:string}[]};
export type TrackerInput={name:string;module:ModuleKey;iconKey:FunctionalIconKey;areaKey:string;subcategoryId?:string;measurementType:MeasurementType;unitKey?:string;customUnit?:string;frequency:Schedule['frequency_type'];days:number[];timesPerWeek?:number;daypart:Schedule['daypart'];specificTime?:string};
export type TrackerOptions={areas:AreaRow[];subcategories:SubcategoryRow[];units:UnitRow[]};

export async function loadTrackers(){const owner=await goalOwner();const[t,oA,oS,oU,profile]=await Promise.all([supabase.from('trackers').select('*').eq('owner_id',owner.id).order('created_at',{ascending:false}),supabase.from('areas').select('*').order('position'),supabase.from('subcategories').select('id,area_key,name,archived_at').is('archived_at',null).order('name'),supabase.from('measurement_units').select('*').order('measurement_type').order('position'),supabase.from('profiles').select('timezone').eq('id',owner.id).single()]);fail('Trackers',t.error);fail('Areas',oA.error);fail('Subcategories',oS.error);fail('Units',oU.error);fail('Tracker timezone',profile.error);const ids=(t.data??[]).map(x=>x.id),recentSince=new Date(Date.now()-30*86400000).toISOString(),timezone=profile.data?.timezone||'UTC';const[schedules,records,links]=ids.length?await Promise.all([supabase.from('tracker_schedules').select('*').in('tracker_id',ids).is('effective_to',null),supabase.from('tracking_records').select('tracker_id,occurred_at').in('tracker_id',ids).is('deleted_at',null).order('occurred_at',{ascending:false}),supabase.from('goal_trackers').select('tracker_id,goals(id,title)').in('tracker_id',ids)]):[{data:[],error:null},{data:[],error:null},{data:[],error:null}];fail('Schedules',schedules.error);fail('Record counts',records.error);fail('Related Goals',links.error);return{trackers:(t.data??[]).map(x=>{const own=(records.data??[]).filter(r=>r.tracker_id===x.id);return{...x,schedule:(schedules.data??[]).find(s=>s.tracker_id===x.id)??null,recordCount:own.length,recentCount:own.filter(r=>r.occurred_at>=recentSince).length,lastRecordedAt:own[0]?.occurred_at??null,recordDates:[...new Set(own.map(r=>fovynDateKey(timezone,new Date(r.occurred_at))))],relatedGoals:(links.data??[]).filter(link=>link.tracker_id===x.id).flatMap(link=>link.goals?[link.goals as unknown as {id:string;title:string}]:[])}}) as Tracker[],options:{areas:(oA.data??[]) as AreaRow[],subcategories:(oS.data??[]) as SubcategoryRow[],units:(oU.data??[]) as UnitRow[]}};}
const trackerPayload=(input:TrackerInput,ownerId:string)=>({owner_id:ownerId,name:input.name.trim(),module:input.module,icon_key:input.iconKey,area_key:input.areaKey,subcategory_id:input.subcategoryId||null,measurement_type:input.measurementType,unit_key:input.measurementType==='custom'?null:input.unitKey,custom_unit:input.measurementType==='custom'?input.customUnit?.trim():null});
const schedulePayload=(input:TrackerInput,trackerId:string,ownerId:string)=>({tracker_id:trackerId,owner_id:ownerId,frequency_type:input.frequency,days_of_week:input.frequency==='specific_days'?input.days:[],times_per_week:input.frequency==='times_per_week'?input.timesPerWeek:null,daypart:input.frequency==='anytime'?null:input.daypart,specific_time:input.frequency==='anytime'?null:input.specificTime||null});
export async function createTracker(input:TrackerInput){const owner=await goalOwner();const row=await supabase.from('trackers').insert(trackerPayload(input,owner.id)).select('id').single();fail('Create tracker',row.error);if(!row.data)throw new Error('Tracker was not created.');try{fail('Create schedule',(await supabase.from('tracker_schedules').insert(schedulePayload(input,row.data.id,owner.id))).error)}catch(e){await supabase.from('trackers').delete().eq('id',row.data.id);throw e}}
export async function updateTracker(tracker:Tracker,input:TrackerInput){const owner=await goalOwner();fail('Update tracker',(await supabase.from('trackers').update({...trackerPayload(input,owner.id),updated_at:new Date().toISOString()}).eq('id',tracker.id).eq('owner_id',owner.id)).error);const today=new Date().toISOString().slice(0,10);if(tracker.schedule){if(tracker.schedule.effective_from>=today)fail('Update schedule',(await supabase.from('tracker_schedules').update(schedulePayload(input,tracker.id,owner.id)).eq('id',tracker.schedule.id)).error);else{const d=new Date();d.setDate(d.getDate()-1);fail('Close schedule',(await supabase.from('tracker_schedules').update({effective_to:d.toISOString().slice(0,10)}).eq('id',tracker.schedule.id)).error);fail('Create schedule',(await supabase.from('tracker_schedules').insert(schedulePayload(input,tracker.id,owner.id))).error)}}}
export async function setTrackerStatus(tracker:Tracker,status:TrackerStatus){const owner=await goalOwner();fail('Update tracker status',(await supabase.from('trackers').update({status,archived_at:status==='archived'?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',tracker.id).eq('owner_id',owner.id)).error)}
export async function deleteEmptyTracker(tracker:Tracker){if(tracker.recordCount)throw new Error('Trackers with history must be archived.');const owner=await goalOwner();fail('Delete tracker',(await supabase.from('trackers').delete().eq('id',tracker.id).eq('owner_id',owner.id)).error)}
