export type TrackingType='Reps'|'Seconds'|'Minutes'|'Distance';
export type RuleType='PROGRESS'|'HARD_CAP'|'EQUIPMENT_CAP'|'QUALITY'|'TIME_CAP'|'REP_CAP'|'FIXED';
export type SetPerformance={kg:string;value:number|null};
export type Exercise={profileId?:string;exerciseId:string;exerciseName:string;group:string;equipment:string;defaultSets:number;minReps:number|null;maxReps:number|null;incrementKg:number;progressionType:string;active:boolean;trackingType:TrackingType;minimumWeight?:number|null;maximumWeight?:number|null;availableWeights?:number[];weightConvention?:string|null;resistanceType?:string|null};
export type ExerciseRule={ruleId:string;exerciseId:string;ruleType:RuleType;condition:string;action:string;active:boolean};
export type LoggedExercise={sessionId:string;date:string;exerciseId:string;sets:SetPerformance[]};
export type TemplateSlot={workoutType:string;variant:string;order:number;slotName:string;group:string;defaultExerciseId:string;required:boolean};
export type BuiltExercise={order:number;slotName:string;group:string;exercise:Exercise;rule:ExerciseRule|null;last:LoggedExercise|null;target:SetPerformance[]};

export function latestForExercise(logs:LoggedExercise[],exerciseId:string){return logs.filter(x=>x.exerciseId===exerciseId).sort((a,b)=>b.date.localeCompare(a.date)||Number(b.sessionId)-Number(a.sessionId))[0]??null}
const bodyweight=(e:Exercise)=>['bodyweight','assisted_bodyweight'].includes(e.resistanceType??'')||e.equipment==='Bodyweight'||e.equipment==='Pull-up Bar';
const activeSets=(last:LoggedExercise|null,e:Exercise)=>{const kg=bodyweight(e)?'0':'';const filled=last?.sets.filter(s=>s.kg||s.value!==null)??[];return filled.length?filled.map(s=>({...s,kg:s.kg||kg})):Array.from({length:e.defaultSets},()=>({kg,value:null}))};
const weakest=(values:number[],max:number)=>{const next=[...values];let i=0;for(let n=1;n<next.length;n++)if(next[n]<next[i])i=n;if(next[i]<max)next[i]++;return next};
const cap=(rule?:ExerciseRule|null)=>{if(!rule||!['HARD_CAP','EQUIPMENT_CAP'].includes(rule.ruleType))return null;const m=rule.condition.match(/(\d+(?:\.\d+)?)\s*kg/i);return m?Number(m[1]):null};
const ruleMax=(rule:ExerciseRule|null|undefined,fallback:number)=>{const range=rule?.condition.match(/\d+\s*x\s*\d+\s*-\s*(\d+)/i);if(range)return Number(range[1]);const exact=rule?.condition.match(/\d+\s*x\s*(\d+)/i);return exact?Number(exact[1]):fallback};
const increment=(rule:ExerciseRule|null|undefined,fallback:number)=>{const m=rule?.action.match(/add\s+(\d+(?:\.\d+)?)\s*kg/i);return m?Number(m[1]):fallback};
export function nextAvailableLoad(e:Exercise,current:number,rule?:ExerciseRule|null){const limits=[e.maximumWeight,cap(rule)].filter((value):value is number=>value!==null&&value!==undefined),ceiling=limits.length?Math.min(...limits):null,custom=(e.availableWeights??[]).filter(Number.isFinite).sort((a,b)=>a-b);let next:number|null=null;if(custom.length)next=custom.find(value=>value>current)??null;else{const step=increment(rule,e.incrementKg);if(step>0){if(e.minimumWeight!=null){const offset=Math.floor((current-e.minimumWeight)/step)+1;next=e.minimumWeight+Math.max(0,offset)*step}else next=current+step}}if(next===null)return null;if(ceiling!==null&&next>ceiling)return null;return Number(next.toFixed(6))}
export function equipmentCeilingReached(e:Exercise,last:LoggedExercise|null,rule?:ExerciseRule|null){const configured=(e.availableWeights?.length??0)>0||e.maximumWeight!=null||cap(rule)!=null;if(!configured||!last)return false;const loads=last.sets.map(set=>Number(set.kg)).filter(Number.isFinite);if(!loads.length)return false;return loads.every(load=>nextAvailableLoad(e,load,rule)===null)}

export function calculateTarget(e:Exercise,last:LoggedExercise|null,rule?:ExerciseRule|null):SetPerformance[]{const prior=activeSets(last,e);if(!last)return prior;if(rule?.ruleType==='FIXED'||rule?.ruleType==='QUALITY'||['Fixed','Quality'].includes(e.progressionType))return prior;const values=prior.map(s=>s.value??e.minReps??0);const max=ruleMax(rule,e.maxReps??Math.max(...values));const complete=values.length>0&&values.every(v=>v>=max);if(rule?.ruleType==='TIME_CAP'||rule?.ruleType==='REP_CAP'){if(complete)return prior.map(s=>({...s,value:Math.min(s.value??max,max)}));const next=weakest(values,max);return prior.map((s,i)=>({...s,value:next[i]}))}if(complete){return prior.map(s=>{const current=Number(s.kg),next=Number.isFinite(current)?nextAvailableLoad(e,current,rule):null;return next===null?s:{kg:String(next),value:e.minReps??max}})}const next=weakest(values,max);return prior.map((s,i)=>({...s,value:next[i]}))}

export function buildWorkout(type:string,variant:string,slots:TemplateSlot[],exercises:Exercise[],logs:LoggedExercise[],rules:ExerciseRule[]=[]):BuiltExercise[]{const byId=new Map(exercises.map(e=>[e.exerciseId,e]));const ruleById=new Map(rules.filter(r=>r.active).map(r=>[r.exerciseId,r]));return slots.filter(s=>s.workoutType===type&&s.variant===variant).sort((a,b)=>a.order-b.order).map(s=>{const exercise=byId.get(s.defaultExerciseId);if(!exercise)throw new Error(`Template references missing exercise: ${s.defaultExerciseId}`);const last=latestForExercise(logs,exercise.exerciseId);const rule=ruleById.get(exercise.exerciseId)??null;return{order:s.order,slotName:s.slotName,group:s.group,exercise,rule,last,target:calculateTarget(exercise,last,rule)}})}

export function recommendationLabel(item:BuiltExercise){if(!item.last)return'NEW';const prior=item.last.sets;const weightUp=item.target.some((s,i)=>Number(s.kg)>Number(prior[i]?.kg||0));if(weightUp)return'WEIGHT UP';if(equipmentCeilingReached(item.exercise,item.last,item.rule))return'EQUIPMENT CEILING';const repsUp=item.target.some((s,i)=>(s.value??0)>(prior[i]?.value??0));return repsUp?'ADD REPS':'MAINTAIN'}
