import { useEffect, useState, type FormEvent } from 'react';
import { Archive, Copy, GripVertical, MoreHorizontal, Plus, X } from 'lucide-react';
import { formatDisplayLabel } from './displayLabels';
import { loadExerciseProfiles, type ExerciseProfile } from './exerciseRepository';
import { duplicateTemplate, listTemplates, loadTemplate, saveTemplate, setTemplateArchived, type WorkoutTemplate, type WorkoutTemplateDetail } from './trainingRepository';

function TemplateEditor({template,close,saved}:{template?:WorkoutTemplateDetail;close:()=>void;saved:()=>void}){
  const[name,setName]=useState(template?.name??''),[description,setDescription]=useState(template?.description??''),[selected,setSelected]=useState<string[]>(template?.exercises.map(item=>item.exerciseId)??[]),[library,setLibrary]=useState<ExerciseProfile[]>([]),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{loadExerciseProfiles().then(items=>setLibrary(items.filter(item=>!item.archived_at))).catch(reason=>setError(reason instanceof Error?reason.message:'Unable to load exercises.'))},[]);
  const move=(index:number,direction:number)=>{const next=index+direction;if(next<0||next>=selected.length)return;const copy=[...selected];[copy[index],copy[next]]=[copy[next],copy[index]];setSelected(copy)};
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{await saveTemplate({id:template?.id,name,description,exerciseIds:selected});saved()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save template.')}finally{setBusy(false)}};
  return <div className="sheet-shade" onMouseDown={close}><form className="training-template-editor" onSubmit={submit} onMouseDown={event=>event.stopPropagation()}><button type="button" className="sheet-close" onClick={close} aria-label="Close Template editor"><X/></button><p className="eyebrow">{template?'EDIT':'CREATE'} TEMPLATE</p><h2>{template?'Workout Template':'Create Template'}</h2><label>Template name<input value={name} onChange={event=>setName(event.target.value)} autoFocus required maxLength={120}/></label><label>Description (optional)<textarea value={description} onChange={event=>setDescription(event.target.value)} maxLength={500}/></label><div className="template-exercise-heading"><h3>Exercises</h3><button type="button" className="soft-button" onClick={()=>setAdding(true)}><Plus/> Add Exercise</button></div><div className="template-exercise-order">{selected.map((id,index)=>{const exercise=library.find(item=>item.id===id);return <article key={`${id}-${index}`}><GripVertical/><div><b>{exercise?.name??template?.exercises.find(item=>item.exerciseId===id)?.name??'Exercise'}</b><small>{formatDisplayLabel(exercise?.muscle_group??'other')}</small></div><details><summary aria-label="Exercise actions"><MoreHorizontal/></summary><div><button type="button" disabled={index===0} onClick={()=>move(index,-1)}>Move up</button><button type="button" disabled={index===selected.length-1} onClick={()=>move(index,1)}>Move down</button><button type="button" className="danger" onClick={()=>setSelected(selected.filter((_,itemIndex)=>itemIndex!==index))}>Remove</button></div></details></article>})}</div>{selected.length===0&&<p className="ui-empty">Add at least one exercise.</p>}{error&&<p className="goal-error">{error}</p>}<button className="save-record" disabled={busy}>{busy?'Saving…':'Save Template'}</button>{adding&&<div className="template-library-picker"><section><header><h3>Add Exercise</h3><button type="button" onClick={()=>setAdding(false)}><X/></button></header>{library.filter(item=>!selected.includes(item.id)).map(item=><button type="button" key={item.id} onClick={()=>{setSelected([...selected,item.id]);setAdding(false)}}><b>{item.name}</b><small>{formatDisplayLabel(item.muscle_group)} · {formatDisplayLabel(item.resistance_type??'other')}</small></button>)}</section></div>}</form></div>;
}

export default function TrainingTemplates({close,onStart}:{close:()=>void;onStart:(template:WorkoutTemplate)=>void}){
  const[templates,setTemplates]=useState<WorkoutTemplate[]>([]),[archived,setArchived]=useState(false),[editing,setEditing]=useState<WorkoutTemplateDetail|null|undefined>(),[error,setError]=useState('');
  const load=()=>listTemplates(true).then(setTemplates).catch(reason=>setError(reason instanceof Error?reason.message:'Unable to load Templates.'));
  useEffect(()=>{load()},[]);
  const edit=async(template:WorkoutTemplate)=>{try{setEditing(await loadTemplate(template.id))}catch(reason){setError(reason instanceof Error?reason.message:'Unable to open Template.')}};
  const visible=templates.filter(template=>template.archived===archived);
  return <div className="workout-full training-templates"><header><div><p className="eyebrow">TRAINING</p><h1>Workout Templates</h1></div><button onClick={close} aria-label="Close Templates"><X/></button></header><div className="training-template-tools"><div className="goal-tabs"><button className={!archived?'active':''} onClick={()=>setArchived(false)}>Active</button><button className={archived?'active':''} onClick={()=>setArchived(true)}>Archived</button></div><button className="soft-button" onClick={()=>setEditing(null)}><Plus/> Create Template</button></div>{error&&<p className="goal-error">{error}</p>}<section className="training-template-list">{visible.map(template=><article key={template.id}><button className="template-main" onClick={()=>archived?edit(template):onStart(template)}><div><h2>{template.name}</h2><p>{template.description||`${template.exerciseCount} exercise${template.exerciseCount===1?'':'s'}`}</p></div>{!archived&&<span>Start Workout</span>}</button><details><summary aria-label={`${template.name} actions`}><MoreHorizontal/></summary><div><button onClick={()=>edit(template)}>Edit</button><button onClick={()=>duplicateTemplate(template.id).then(load)}><Copy/> Duplicate</button><button onClick={()=>setTemplateArchived(template.id,!archived).then(load)}><Archive/> {archived?'Restore':'Archive'}</button></div></details></article>)}</section>{visible.length===0&&<div className="ui-empty"><p>{archived?'No archived templates.':'No workout templates yet.'}</p>{!archived&&<button className="save-record" onClick={()=>setEditing(null)}>Create Template</button>}</div>}{editing!==undefined&&<TemplateEditor template={editing??undefined} close={()=>setEditing(undefined)} saved={()=>{setEditing(undefined);load()}}/>}</div>;
}
